#pragma once

#define WINDOW_HEIGHT 600
#define WINDOW_WIDTH 600

#define SPRITE_SCALE 0.04

#define MIN_BALL_SPEED 50
#define MAX_BALL_SPEED 500

#define IMAGE_PATH "../SCP.png"

#define FPS_CAP 60

#define FONT_PATH "../Daydream.ttf"
#define SDL_FONT_HEIGHT 16

#define FPS_TEXT_POSITION_X 20
#define FPS_TEXT_POSITION_Y 20
#define FPS_TEXT_SIZE 10
#define FPS_TEXT_SPACING 2
#define FPS_COUNTER_SDL_TEXT_WIDTH 150

#define SWITCH_TEXT_POSITION { 20, WINDOW_WIDTH - 20 }
#define SWITCH_TEXT_SIZE 10
#define SWITCH_TEXT_SPACING 2

